sudo: false
language: node_js
node_js:
  - "4.2"
cache:
  directories:
    - node_modules

addons:
  firefox: latest # Needed to support react

install:
  - "sh -e /etc/init.d/xvfb start"
  - "export DISPLAY=:99.0"
  - "wget http://selenium-release.storage.googleapis.com/2.50/selenium-server-standalone-2.50.1.jar"
  - "java -jar selenium-server-standalone-2.50.1.jar > /dev/null &"
  - npm install

script:
  - npm test
